services:
  postgres:
    image: postgres:16
    container_name: postgres-autenticacaoapi
    environment:
      POSTGRES_DB: db_autenticacao
      POSTGRES_USER: user_coti
      POSTGRES_PASSWORD: user_pass
    ports:
      - "5434:5432"
    networks:
      - postgres-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  postgres-network:

volumes:
  postgres_data:
